---
apiVersion: v1
kind: Secret
metadata:
  name: salsa-latina-basic-auth
type: Opaque
data:
  # htpasswd line: admin / salsa2026  (bcrypt)
  auth: YWRtaW46JDJ5JDA1JHlFaW5SZTRKNHhLTE5MYmJvSGx3WC56VE1UdXJjVHJjMjhuRFJDR3NBSXlrWDRZN1dLUGoyCg==
