apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-salsa-latina
resources:
  - ../../base/v1/
  - basic-auth-secret.yaml
  - backend-secrets.yaml
images:
  - name: registry.gitlab.com/josmarr/salsa-latina
    newTag: main-7a7102de-16276670167 # {"$imagepolicy": "flux-salsa-latina:salsa-latina-stg-ip:tag"}
  - name: registry.gitlab.com/josmarr/salsa-latina-backend
    newTag: main-0ffb4559-16276680545 # {"$imagepolicy": "flux-salsa-latina:salsa-latina-backend-stg-ip:tag"}
patches:
  - target:
      kind: Ingress
      name: salsa-latina-ingress
    path: patches-ingress.yaml
