- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: salsa-latina.josmare.fyi
- op: replace
  path: /spec/rules/0/host
  value: salsa-latina.josmare.fyi
- op: replace
  path: /spec/tls/0/hosts/0
  value: salsa-latina.josmare.fyi
