---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aika-basic-auth
  namespace: staging-aika
spec:
  encryptedData:
    auth: AgBY44jGn3AJPDy9T4sapckT2whuTfePGpEIdkQWac5pXdxLyU2Pki6wJ8CXzTqpk8DiHruzgze6QYpgPJ4RyK0EuO+Hj5XeQlF4XI5T8zAJmC9UE9o2t3C4XC9sNh6BTqQSVXCy7bBDu9MqlmE3iZBIpWVLrQCPRKxHDAh38yFe7ZskDTSlQEN9x0N4r+lNFrHY1jcULQiTugqItuiMNgoqvOtGIo5z/rX2GUd4W7i5r6aUL2OZDi8vqLttuE8NC+tqK9Gy+wXkeMNa6PaTESqC95hEikbic9Vi9MJQOh8FnHRqNAx15Jw2vC1aE/dEgtJq31RCHfDYQGqprxafpwtGV22a00p65rdCHzy0FzfuiPZeoHak3Z4qILY4vz2WtvZayS3mUWm1UrWs7/xw6XI/tl5CtC9bYKzzK9oyA7/FHnbgIcpCiq4G35gbGE1TDkj/7crZrqf5yAeCwpzUz0+F3YbnGzfLnl8dQ0TQMWtioWdohsPsQX3UTOd6VhW2Q1qQa9Sut1qmgTCcctkPkX/GtPA8Fq5ICR2xfDItH+hZH8NObFnZj9HoerOz3+XKsYCB7AS4BVjE6PbIsGEacLFJpfkyN/Dk3lTEZ7Rfv12tpMEhuIkupvLy4s7/rXzmPtH9T7QVqVoc+1hhJuzlD8vjagI2dZKOw5yeD2do0VCyKXsBI0KpEleqNikqbgHw3q63s0Ba+x5otzdN7NL+pAedkKbWep+HwE19cMHe+SoJcBLTY03koPpq9Pa4RUoTw1XKZDtMPGSkCi+EemhSPZk6H8E=
  template:
    metadata:
      name: aika-basic-auth
      namespace: staging-aika
