apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-aika
resources:
  - ../../base/v1/
  - aika-secrets.yaml
  - basic-auth-secret.yaml
images:
  - name: registry.gitlab.com/ezbaa/aika
    newTag: main-84cf5c19-2882156890 # {"$imagepolicy": "flux-aika:aika-stg-ip:tag"}
patches:
  - target:
      kind: Ingress
      name: aika-ingress
    path: patches-ingress.yaml
