apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-aika
resources:
  - ../../base/v1/
  - aika-secrets.yaml
images:
  - name: registry.gitlab.com/ezbaa/aika
    newTag: main-c5cb664-1789654432 # {"$imagepolicy": "flux-aika:aika-stg-ip:tag"}
