apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personal-page-app
  name: personal-page-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: personal-page-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: personal-page-app
    spec:
      containers:
        - name: personal-page-app
          image: registry.gitlab.com/josmarr/josmare-personal-page:placeholder
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 80
              name: web
      imagePullSecrets:
        - name: josmar-ips
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
