---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: josmar-ips
spec:
  encryptedData:
    .dockerconfigjson: AgBH3Gwh0KwJUJf2/6eH+dTtPvah7Q3ZXNedkF3+wPPKCw4ts/Wcv4UpS8KbZRXR56aGDTWR52qNvWKaG3OFdYT74PUWrORuE3W4thBAhsXzXtPDEUlfrtQmDEz5B8RAsVgAIXIODAKbchMosazP0c6x8GvvxF3/ZpZwnYCJ32TtqY+dThTaNyuXHeE6ZPZ9FO3KvJ7q9PD/3jAdJBQta1eZgIJAfudPD5n3879H2hiqAAcVnLG1yHkQzgeNhu+qOQzK6Vp8Ao4HIkyU7QUd/hLwoHySkZIYOtb9Ozg4Tir1FDLGnzIqU/wy+9Ux8YbBn1QU25JuNjDauEwTd3ETbjSosFzmhZIAKN+jw6pe9krWygqDs9W2kmitxDGGPpr4Z63dokoiJVJAhCP+4boYP9LXw5yCB1vyNeeiR93eX2XWBYapQ85Sm65qDfutx1ljChngEIckusYDVTICnioj7xoUhWydlpqlRaB0LGh28jcONW6fDHh03JKn7+ueel84bsc1JfP5AIav8xZpPmVjcf4GwjTR6D0j9qIisADGEuXBcH8YLNS12omgoi+/NqSks7GJOPbRE1TDWH1qUcN2basjXDPbOONluhuo6GTR4Nz1h7koDzPZWMdnPQKhZsT021AAyXW4GODZSiLsOHMSXcIrWGRE2Zjmykzqq+Y61gOwrHSUax6JRiYDqhhJ1yZiZ5UnCZn7Y45LOrzlp2XxWu38TjId4hoqdOwczibeikVnaoMymMoB26eX67xxMQMoqoFkOVCtYjrA9L+CUK/4EsqiTdOSYu9RXiKHMZ0kWJ6yN6WjgnpUX5YaS4sDu4FH/MHwRMX2/9A8zGCvyy7G+wHaN7ilhWWlvuluA6pG4/EY33Q1ylpwCSw/4vtefqvld7P1PoNYnzvjp4vLSmUq1tri/3dCv0yWLuoXEwmelGDlhUqralRJE8PpdHyZUa1HwDSz7ufmAH79AhWQLNPzkDk/ikHGXLuZ7W6cbYI55rbVnBu0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: josmar-ips
    type: kubernetes.io/dockerconfigjson
