---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: PLACEHOLDER
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
  name: personal-page-ingress
spec:
  rules:
    - host: PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-page-svc
                port:
                  number: 80
  tls:
    - hosts:
        - PLACEHOLDER
      secretName: personal-page-certificate-1
