---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aika-db-credentials
  namespace: databases
spec:
  encryptedData:
    password: AgCcxHdsaQogBgUrs9QMOEoizrqXD0T8tZoHED4sBTKK2usm3klKRQvRgXOHUMaQKRcrvirS4ksrX3ptbIeJP+QSE2nZqatGSW0o5oKvsQ1JdRURUMa/Vs0dJFoOHGVGNvV0jsvYkoeifjw3KWOADcYJbmuYsdAK6vukULoxyfaN28omRvf17U6QyKMjuhmvPc5tAfn9MJQl3IX5E6i6PtXgO6Wc7XYqQ4GorSmxSzHba9z8/WazANTbo/2F5jTZmsNA0owS0VdWCNT24JW/FS0hrZpOQ3uZC66ch/MNzUU2xVl6ehNPNgX24L+VcR00GIgNd1rwFYT/wNrcoHz/ewTIui9PtIFVy1hgl3tC0pS7WR5gRZSMX74cmmRpDRxazckONPxRsjnJSVrAT3vNWikHIZW5DWSzPGtksLYc6hS5JMqVRkjOlTedGMisYasBHwqDOlgDZ0CpSbEwHIiwDIj1prn1EDzrP8a5UaSxieJILU/LZDv8W4PoTUpU1vdRXnMfWfrt7JNLaFBF2CyuMmb9tOzx225dxVOxDMa6d6zDg9dPjahGUCnKYwdA1z+VULhVyMwoYSS3ElLip1x9IDqHUnmHEaO0CAHBn4vaQwMUYg+d5wn4B8+ucTabCunFPtsh2nK0Q7BESwWn+wbHy82m0L0fF9iJuktIZg8tbbuOKHzHs8+CX9sOFR3p/M2HBGQHTyDpqkYKlDtjr2KPrhBIEqwXzPlcKx/Wjt3b+pfl
    username: AgCRIyPgy0M785FtZTEzlqTX0ZXBSR3VaCdJaINwML0fsHtGs4GAR8eYEIBi2x/lxfFaG/wnpBZOjuvZmVou+CX/5+h+tTuTQ0vPRUPu8KFe4k3LGu4kulxH7WOrcMDKwqpQojZrNW5TEnu4+n+sI3vA4bZPGQldQFt7OYIpa2kDb6ItKXVIrDg85891UjTt0o8twg7vsKMubD+BMsxmvfKhTeAgsDcOj0gV7ZN39jnoZNiQamh7p5jL+3iEmWVzoOWXpqUf/0HblBTsawI8yalf1V8eOX4qHCkE29dYEVOiTGiUGiD4rPtyebVNwlvkliZBo7iCw4taK4PnEAlByA3r2YE6uO97DtfzoBNeZlF3Bdow/0wpMRmu0ZzhY8CgkWyLvpm+FFy9AqBBCNzNzrlyt5qXy8/IukJO8icUZRdhIiRjcYtROG+ASTLOCZsRL6fZ2zGP149xqm1matjWFkiYjI6v9OAr0MS86OtVOlfSKTJB52AdEdxYQQ3VEG4toK/CZoS5zDLqqcPCTDJIA/NSwPuFsc+Syb6QolwU34dTT+DcGFI99R72DKKYljFbbSPMky1oR4YPeBDoWB8f+dMjT7iiMbENp0PM9HlDboIBaUlT7/EGbQhsH7TAwTpI8Iw7oiOa50c/L1vAuD98SrHuDd3BaZT+ehh6TqX3L2l0BFvg6DUx4wLeOa/H0AhUXtxnp0zC
  template:
    metadata:
      name: aika-db-credentials
      namespace: databases
    type: kubernetes.io/basic-auth
