---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: salsa-latina-db-credentials
  namespace: databases
spec:
  encryptedData:
    password: AgAUWkDwMxegjv496UTjR580W6vuDvNuo62XM9NvvpxwjKeVntmxOt79unJ0SIS5aK0Aw8nY7WdTHHDrsfxyITMSkV9zSZeMojuFhqBj0daCBqoWOOmtdqjz0OBAkQ9JNnw+GEjXjO1RKuGukXCPSAr+VcoDw22wB3yzNC0hkCs69438FKVMAyRfBej/GBrQADGonrN7waKc9YhBWoa0qqm9+7sgE9vBeljghBJkm+I5T7QWZEx96wgcG2BD6ZYrhybaILkexqbNlYXBrvBezLFCXOY/U37JmthkiNEtXVLU3BcpP08xyvFDTwIFeoTbMj9v3cLtQkfc66Ql0De1jjEsppo3G7miinAxNJaum5g0t4X/xQgzJdyp9mpUN+htspmq8qlzS+dtYNbk9wWOqvtEyH9B+g3gw9bYElVodUenZ7P6QQztKbEKj2jJDKNgp4ml3urCM1PpNOPM1mcMfFWX2PI/y87VpUy9d9J6ewQk4jqcii1HkDfiUwjSdoja521D6ka8vzKfbWsQWch5CPi0pJO4jW/vkUz/NApruLxdKgg2SyCkWthnGBdMOz8weJB1rRZrRaElBEjwMeb4lZaObgmbqI8qFQRy99cofSK58UgecXG8h/Zkam8rstZVhPVEKz8P8wWlYveRmvbrhWnByUlsnBCmjwihxigNssSYw76EyarRAWrUnwm9PEnRYXeIfuzA8tBWUcw1vnta3sGwyol4DAhbmAlULOw6tm4fhs2kqbYm+Vu+
    username: AgCLLXQWrYFca2xtfvTj9Za47oGL0Tp90WPW06UZjmY4E/R/8nIrhNDCh7MCtihxxEtkiemCmrIJQJZqsh9D0J75ETVsk8zVrboYzRPKPlvYUi1Q4DY7fYsLEoVr2kiWXjtxENR1wZl6ohcP14d3ZNQyh37mKtJoXUb1xW4Z9nbMcjHljz6MgGKFaID/JxsmWrR1izgL0mh9ThplfUqEm38RaOJ386SpN+mnNjMvE1JcOZevB5gU/F3sztanoQi+8RyqtxbGf7berpNGrXCipNg/o45GgLhbHVnRn0s8R0GbSf7n18VKOej0XFHZi2yu0dbZVxQOnEcFMY+Trk/mqnFFeao2H/7QV3fwDArf56tiWN1ZEP/6m349VPTm1TY0BPj606xc6vvhx7bieP+UU0ts1Cdlh6j8z24Hwve+sWeKVnISlKZih1qAchw4eii2alwZthdksoP6N1WOjv8FDi1hZj1LOqqMkTkBqL06+DEQMkXhQhgwNa+5I4okCnADEnc9AjoWHq5l4RYV4eCWgaK9EFwtpNETDB9XA8KZQOz37SwF4QnWEBTcw9nOiiUI1d2lbqig5hJgm0AC1olDug5W91tyIvDWp9uIQVElLtJdMmYx3wJycC55cMBJ4jb0z7TP1aTeRlVpmtuewRAAAXDoxO9g2I7zryEofoO7FX5xPFLSK86qB9+Rmpl27QF88bs+u4+gdzyfWqLeeg==
  template:
    metadata:
      name: salsa-latina-db-credentials
      namespace: databases
    type: kubernetes.io/basic-auth
