---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: salsa-latina-staging
  namespace: databases
spec:
  name: salsalatina_staging
  owner: salsalatina
  cluster:
    name: shared-postgres
