apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/v1/
images:
  - name: registry.gitlab.com/josmarr/lohko
    newTag: placeholder # {"$imagepolicy": "flux-josmar:lohko-stg-ip:tag"}
patches:
  - target:
      kind: Ingress
      name: lohko-ingress
    path: patches-ingress.yaml
