---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: josmar-ips
spec:
  encryptedData:
    .dockerconfigjson: AgAYWF0SKamxwJ9bQaXZ/vqLOdD+lcbF8edJO2iUrjc26dcBFuoWDZWoJ5I5OKFd5/zlzXnJlJpKzEhVkDP9Z3zkfRpDKxPklo1lVskl+X1SspzcjtcUGtac/UZHMHvcySJK/SHpPt7RbpqRkrWO7mZYKCcfp8cLhq7s3txZiJew56QV46vHjsNxxppZRo9M07CZFL4dUCB9Nb4ffJHyS+3LGG/z752cAWBlqfxJWH6CxvME0AdnyGI3VzaT4fLnQk/2VepszxHp44gm+QL0nty1nMWYFAQf7Gi3XpxisFtkgq0y7x6Dmx1bwN7NBkbPAR+WQjdFvBRTy8iv3O7tHvDZy1aDoYVc+J51ZLGpW31BWU4IkSSvVtWBIopB5tnFLq8oXeezNWnyKvMhAzBJPjOunyVFQB1oXr1VPEsSCVwOFs7NIIhfkq2jyuyvaPBhHv5sOdqPwwpgS+n0iXPPPu+PY669C+iQOcyxw5YkApT6LmOYBZPNKB0QguNY+zfKKSi5COH1sxfbR8FJhrKpsPmZuEBQqOpoceIzO3B2ZOfUXzE/2rWN7pIMjic64rS2if6MVXmRaUPi09hgz9VRPe+NCYZrEcS8fuBv5XFLtXz3F+Dm5pTgJsPcfX5e/bO4GKVrJ7nWdvmnPbgGLl6UFIeyLoGMWED//rU9qgdDbO4YasHZFEyH0u1vXZiJUIQlfSw+b+TzYsZuvuFbGOLUXZx98rJDTvFApHB5pXX4XaSlFlbowoSKoNCfoIVQDDt1bMNdsaMhv8z7eOmt/NRHdTV5GOhS/tWfR3dKoI1HLOIkRm5nlV2R1DllsHmJ5d2Y8bLqb3YQR8vG7z375J6HBZAjZV2YJVxm/PuWUii5ldLobNDph25w08B+xBpahiPJzqRFNUtWtT6j/M/RetYLke/G6bd5elJBxYAoV1E6B7gTUXr8khQDUQvwyeCbP4MWDDvqWhuFUagwOpaR5gqz0WyXuoM0Gl+J0+yYHlWgD0MiH1sceuKpjX1SKTzssLn1l2Wblqo9K1rgc93c39Qo65iiRTgMcEg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: josmar-ips
    type: kubernetes.io/dockerconfigjson
