---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: josmar-ips
spec:
  encryptedData:
    .dockerconfigjson: AgAYWF0SKamxwJ9bQaXZ/vqLOdD+lcbF8edJO2iUrjc26dcBFuoWDZWoJ5I5OKFd5/zlzXnJlJpKzEhVkDP9Z3zkfRpDKxPklo1lVskl+X1SspzcjtcUGtac/UZHMHvcySJK/SHpPt7RbpqRkrWO7mZYKCcfp8cLhq7s3txZiJew56QV46vHjsNxxppZRo9M07CZFL4dUCB9Nb4ffJHyS+3LGG/z752cAWBlqfxJWH6CxvME0AdnyGI3VzaT4fLnQk/2VepszxHp44gm+QL0nty1nMWYFAQf7Gi3XpxisFtkgq0y7x6Dmx1bwN7NBkbPAR+WQjdFvBRTy8iv3O7tHvDZy1aDoYVc+J51ZLGpW31BWU4IkSSvVtWBIopB5tnFLq8oXeezNWnyKvMhAzBJPjOunyVFQB1oXr1VPEsSCVwOFs7NIIhfkq2jyuyvaPBhHv5sOdqPwwpgS+n0iXPPPu+PY669C+iQOcyxw5YkApT6LmOYBZPNKB0QguNY+zfKKSi5COH1sxfbR8FJhrKpsPmZuEBQqOpoceIzO3B2ZOfUXzE/2rWN7pIMjic64rS2if6MVXmRaUPi09hgz9VRPe+NCYZrEcS8fuBv5XFLtXz3F+Dm5pTgJsPcfX5e/bO4GKVrJ7nWdvmnPbgGLl6UFIeyLoGMWED//rU9qgdDbO4YasHZFEyH0u1vXZiJUIQlfSw+b+TzYsZuvuFbGOLUXZx98rJDTvFApHB5pXX4XaSlFlbowoSKoNCfoIVQDDt1bMNdsaMhv8z7eOmt/NRHdTV5GOhS/tWfR3dKoI1HLOIkRm5nlV2R1DllsHmJ5d2Y8bLqb3YQR8vG7z375J6HBZAjZV2YJVxm/PuWUii5ldLobNDph25w08B+xBpahiPJzqRFNUtWtT6j/M/RetYLke/G6bd5elJBxYAoV1E6B7gTUXr8khQDUQvwyeCbP4MWDDvqWhuFUagwOpaR5gqz0WyXuoM0Gl+J0+yYHlWgD0MiH1sceuKpjX1SKTzssLn1l2Wblqo9K1rgc93c39Qo65iiRTgMcEg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: josmar-ips
    type: kubernetes.io/dockerconfigjson

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: salsa-latina-backend-ips
spec:
  encryptedData:
    .dockerconfigjson: AgBtjm8CoUD3Khz1g8nl2JXsi07WQ2jztUAipzZat0ybcurlgfQsTymqbKGOPLMhrUS0Oz7qAb2yCx3f0X95Vk0yjHslc8Bw50fSfb4BhsC65oHvvOAIMo4wlv/e/Tq/VaxiU+E8O+KmzCD9O98l+UmpbUXhVlk/X2aFCLjzJfy7HHkFgH3vDUSBtP3lZR0vOaMZ24I2CNcjN/2wEKiiwrGU3vb2iVoituxvVDjvIbSXDpstcV3lSBWJeKwivf3zJgyHigE/km88ETMXMfGbj+Z3/Aj3uqSDPSYAC5x2/Amk5jeILHDZx3YRLqhQc2vKoLOEBWPpxwQBPJBvBz39rAw8GNR6/wjatfjb5Om9wznb0JDd8M4JdNHE9ppV8uJnJDGTmiCrLFOFkNjm2KDNHNSX+oEtfz0MNgn4Lu5qXwofxWgl8sSemxQGoVWWuWl/1wc0YOfXp7yDu4/bmON20Ar2mEkRrAAa+UDmBthk/xRFINks3bgcCjtdgNBZef11/XxDgOAYV+DfiuLRPGFdqUjmDvA/q1zsoH2WAkUkhUG0Wv+pEzJ/Ei5h3i9pKXLUv+i96PUZ0qD62SYLWcPkrnVpiwUy0MmtH/rtoLhijUxV7M/DiT1pcpSRvMlCai7aHFUnJKgv0gxFK5a7tVdFP3Zge0C+Rci1TOqZOPKU08faxC4gVwG8pHfsZ4dplOsNlGQ8+E6bQ+o50+jI0wtI/as+Dd1ZmSqOm6ogVAph3KLBlHQTUpHFhsg+ai+wr/8QtHeB+2Jtxv7MA2tisF+W3zprQa/kbSLzQh/DLs+CA0tyK+KMOCC3o7lS5OEnlRkLTbiDsOO2/BO+9Or4LIo/omegQihM/mPQhmk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: salsa-latina-backend-ips
    type: kubernetes.io/dockerconfigjson
