apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-personal-page
resources:
  - ../../base/v1/
images:
  - name: registry.gitlab.com/josmarr/josmare-personal-page
    newTag: main-0000000-0 # {"$imagepolicy": "flux-personal-page:personal-page-stg-ip:tag"}
patches:
  - target:
      kind: Ingress
      name: personal-page-ingress
    path: patches-ingress.yaml
