apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system-automation.yaml
#  - image-policy-production.yaml
  - image-policy-staging.yaml
  - production.yaml
  - source.yaml
