---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: josmar-ips
  namespace: flux-salsa-latina
spec:
  encryptedData:
    .dockerconfigjson: AgAIYMaoCLNge3nDrBIxnsO5R8pNwcoy/YTDGMCJ7+CDMoPSkmD+tFpdkgUrOSUoi19eJIyddBb3jKmL/A5SlzmoxNNStTS16Noa9Muf0RHM96yQMGs8cFHt0pdjkqKxrQM0WJWimhIkRKa4aafjVppnqKUmcE7/icEJwIbhplcHP+EOcLYTnTjmn7RYSLvhFy1HVRtZCrWMmNBMDAx3mBQuVncWcPU+k1um9tTZ9AwulL5dHuj6x4lGAvl6JgwSS12p2y7pWXlGFM5S5HLBJQU8yY3O55uRoZuKEqB3IzaLvfwvd/DMDu6l81HrEcyF0XqkYwLXr5jjO8e7/quUqf2Xi0nHFyTmRnVy8SqYtXmkUG+jUTPFnEuZ8PzHiCrhwAg6fs7Wr5BC1hnXSSPT+Pets8I4Xb4xRym452K2Z9X0yvkejEi05ZM0n+ieVOPjp711VvTXzW/HhpB3H4c2nR8G+mTnwFAMRjyMiOqx2j05ldsbZPCGYGfnD1TVT5hftAu6F5VyDcgjYL6mMyd7B5asj9mHKgUAU+V54zltis9hZv90lVuWxD3r968gF2baKKMJeRCq62cIyw4b4OzJRzJixbmjxwMNrH4nKTqJF6E5GdVZYGyoEhV+BjZ81FMCH438mv3Sqb++UsNhXABU74S4HS631Qvd5Lsl1qOB1ezFzvsX+2AobP7nTY35Apv62tm0I+hJRDMzKV/Z3K1vLCpw3P8fZWB52lYb1s3vXdm//U3TrEmWLXtMf4YDN94NVbS9v/IquDOQd0I2DAVJWCthEk6ICNHiKEdtTkTMXpR7R2+d/MLrype9INnGA33jglEtxjfz8HgFh6dOXPsxzmEYrHRbx786YNHu/O36zxcOhFCKcGs5KOkqtIgmd6pO9ysHsAtE5Lw094i9o6o5f+jxWV3J1ITCrexJ5pPiYGTPOFtWoM0ohXKus6kfE6ddrzMn21z4bTs7rLHeL7xpG9gp9Pd6bW6r1uF32bV193aHeF0WYsM8eVjGa+E7UgXBQHhuhNQOtJ4HOQDe2cQEb8rgEWM3RLY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: josmar-ips
    type: kubernetes.io/dockerconfigjson

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: salsa-latina-ir
  namespace: flux-salsa-latina
spec:
  image: registry.gitlab.com/josmarr/salsa-latina
  interval: 5m0s
  secretRef:
    name: josmar-ips
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: salsa-latina-image-updates
  namespace: flux-salsa-latina
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@montel.fi
        name: flux
      messageTemplate: |-
        flux: automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
#  update:
#    path: ./gitops/salsa-latina
#    strategy: Setters
