---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: josmar-ips
  namespace: flux-salsa-latina
spec:
  encryptedData:
    .dockerconfigjson: AgBjQsJFPKydOIjKn9pv+Pd7F0vLIJPbNapX38aBNWK2LmcmTqTL/u+uDQWRJx3jk20sqXO4SBoZNM95qebcOT1GtzT6vp5VEu7F5JymxW1t0LSSt9lEbkYHI4s6005instVHBY+RIRlAzimOpWKIAGTyjPAL1LdHB68VBKX1d56nPojZ9IlKt5g3LoeAYqqBbk3PgEXGajoCp9zF4LEhb1cxSvcPKPfW58PatMVndAzCKDZdaAu+bJx7Aq6zqwtf9LOyPP+XUd9lIZUB1AuRsEAygJVbGHBljWoMXbhxPFaL7hQhagQzozKkDSijtqqN9CXDtCIaKaPlJ2Xx2dsyT1M11i+9RCLbxmSb4FGcniwjs4qATA27apLCIT+1vFqOPLoCypYVGJOLGCaCdqWPGVtXcW8bJLkNbIyd+4z0EyMUR2ZGCTa+MdxAFxpHeWZUnqsueMGDOzoVcSeb267zjV9sybFnxpHFcEpW6foGOwMyvsBVdYap7ED932AaMEI/WJhMCxnjL9JoJhGVaFkszG+CN7vwTfxJoTTViK1mrEB/J1wKgWyvWFwfbzlUCVBTVmFVI7aby58oXFbQ/9DS4ynq4mwGoRbLSrplK4nuTpW5XVUN/AVZ3nMEUrBzJiNZ1Wtug2Qjaf/blBsvhvn6YgZoM3c6YT+DdsF3uzYX9U5cYMLVuIKnF+Nevcf5/mmb6ZHLZz3xyoWgUML8gVK3qJuMNwi38rI0VjUqqvwVMfpBXdhGqAWHrVLRnajMR6YgdbDs9tvL5FHXD8jJg8SKyFrvgcVZ8ztE/0dELUY4h6Rjkx3yCE5cQBtV5mc5Z9axbbFTZCsrK5lfncEwjPU0TSPqn41AFau5YmM2dg7fqlYextYljMq+cyNfoTLylg2vauuA6r1ugGjNnp0wHRNT/uDGH5uZ03Jx7GyVHuhL0/2mbTdYh5FE6EJmbKZyaLzcv8sWf3Yy5zqITmNRe1SLMOpp0TevvIq6VOGEFQLYMEB59UuiIqKYCGhrMOtbhbYk7w3BNEwprMruC0s3o0cP6sIpPBuaJ8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: josmar-ips
    type: kubernetes.io/dockerconfigjson

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: salsa-latina-ir
  namespace: flux-salsa-latina
spec:
  image: registry.gitlab.com/josmarr/salsa-latina
  interval: 5m0s
  secretRef:
    name: josmar-ips

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: salsa-latina-backend-ir
  namespace: flux-salsa-latina
spec:
  image: registry.gitlab.com/josmarr/salsa-latina-backend
  interval: 5m0s
  secretRef:
    name: josmar-ips

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: salsa-latina-image-updates
  namespace: flux-salsa-latina
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@montel.fi
        name: flux
      messageTemplate: |-
        flux: automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
#  update:
#    path: ./gitops/salsa-latina
#    strategy: Setters
