---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: salsa-latina-stg-ip
  namespace: flux-salsa-latina
spec:
  imageRepositoryRef:
    name: salsa-latina-ir
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
