---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: salsa-latina-backend-prod-ip
  namespace: flux-salsa-latina
spec:
  imageRepositoryRef:
    name: salsa-latina-backend-ir
  filterTags:
    pattern: '^v(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '>=0.0.0-0'
