---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: salsa-latina-team
  name: production-salsa-latina

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: salsa-latina-team
  name: salsa-latina-team
  namespace: production-salsa-latina

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: salsa-latina-team
  name: salsa-latina-team-reconciler
  namespace: production-salsa-latina
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:salsa-latina-team:reconciler
  - kind: ServiceAccount
    name: salsa-latina-team
    namespace: flux-salsa-latina

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: salsa-latina-production-fks
  namespace: flux-salsa-latina
spec:
  interval: 10m0s
  path: ./gitops/salsa-latina/envs/production
  prune: true
  serviceAccountName: salsa-latina-team
  targetNamespace: production-salsa-latina
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
